[package]
name = "shop-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
#for getting data
mysql = "22.2.0"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["handlebars", "tera"]
